"""audit fields: social profiles, review position

Revision ID: bd77fd591dc1
Revises: 12cad5551b1e
Create Date: 2026-10-06 21:06:24.315950
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'bd77fd591dc1'
down_revision: str | None = '12cad5551b1e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('social_profiles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('gbp_profiles', sa.Column('editorial_summary', sa.Text(), nullable=True))
    op.add_column('gbp_profiles', sa.Column('plus_code', sa.String(length=80), nullable=True))
    op.add_column('gbp_reviews', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('gbp_reviews', sa.Column('relative_publish_time', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gbp_reviews', 'relative_publish_time')
    op.drop_column('gbp_reviews', 'position')
    op.drop_column('gbp_profiles', 'plus_code')
    op.drop_column('gbp_profiles', 'editorial_summary')
    op.drop_column('businesses', 'social_profiles')
    # ### end Alembic commands ###
