"""project match fields

Revision ID: c8e7ef7a265f
Revises: df2af6f3d7ab
Create Date: 2026-10-06 22:10:31.400284
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c8e7ef7a265f'
down_revision: str | None = 'df2af6f3d7ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('match_status', sa.String(length=30), nullable=True))
    op.add_column('projects', sa.Column('match_confidence', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('match_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('projects', sa.Column('mismatch_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('projects', sa.Column('match_candidates', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('projects', sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'matched_at')
    op.drop_column('projects', 'match_candidates')
    op.drop_column('projects', 'mismatch_reasons')
    op.drop_column('projects', 'match_reasons')
    op.drop_column('projects', 'match_confidence')
    op.drop_column('projects', 'match_status')
    # ### end Alembic commands ###
