"""initial schema

Revision ID: 12cad5551b1e
Revises: 
Create Date: 2026-10-06 20:37:30.736348
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '12cad5551b1e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_usage')),
    sa.UniqueConstraint('sku', 'day', name=op.f('uq_api_usage_sku'))
    )
    op.create_table('data_sources',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('request_params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources'))
    )
    op.create_index(op.f('ix_data_sources_expires_at'), 'data_sources', ['expires_at'], unique=False)
    op.create_index(op.f('ix_data_sources_fetched_at'), 'data_sources', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_data_sources_request_hash'), 'data_sources', ['request_hash'], unique=False)
    op.create_table('businesses',
    sa.Column('place_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('is_client', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('raw_response_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['raw_response_id'], ['data_sources.id'], name=op.f('fk_businesses_raw_response_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_businesses')),
    sa.UniqueConstraint('place_id', name=op.f('uq_businesses_place_id'))
    )
    op.create_index(op.f('ix_businesses_domain'), 'businesses', ['domain'], unique=False)
    op.create_table('business_locations',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('formatted_address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('website_address', sa.Text(), nullable=True),
    sa.Column('website_latitude', sa.Float(), nullable=True),
    sa.Column('website_longitude', sa.Float(), nullable=True),
    sa.Column('pin_vs_website_address_distance_meters', sa.Float(), nullable=True),
    sa.Column('is_service_area_business', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('raw_response_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_locations_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_response_id'], ['data_sources.id'], name=op.f('fk_business_locations_raw_response_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_locations'))
    )
    op.create_index(op.f('ix_business_locations_business_id'), 'business_locations', ['business_id'], unique=False)
    op.create_table('gbp_profiles',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('business_name', sa.String(length=300), nullable=True),
    sa.Column('formatted_address', sa.Text(), nullable=True),
    sa.Column('map_pin_status', sa.String(length=20), nullable=True),
    sa.Column('maps_url', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('primary_category', sa.String(length=200), nullable=True),
    sa.Column('secondary_categories', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('opening_hours', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('special_hours', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('business_status', sa.String(length=40), nullable=True),
    sa.Column('service_options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('accessibility_attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('photos_count_available', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('raw_response_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_gbp_profiles_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_response_id'], ['data_sources.id'], name=op.f('fk_gbp_profiles_raw_response_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gbp_profiles'))
    )
    op.create_index(op.f('ix_gbp_profiles_business_id'), 'gbp_profiles', ['business_id'], unique=False)
    op.create_index(op.f('ix_gbp_profiles_place_id'), 'gbp_profiles', ['place_id'], unique=False)
    op.create_table('gbp_reviews',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.String(length=512), nullable=False),
    sa.Column('author_name', sa.String(length=300), nullable=True),
    sa.Column('author_url', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_reply', sa.Text(), nullable=True),
    sa.Column('review_url', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('sentiment', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('raw_response_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_gbp_reviews_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_response_id'], ['data_sources.id'], name=op.f('fk_gbp_reviews_raw_response_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gbp_reviews')),
    sa.UniqueConstraint('business_id', 'review_id', name=op.f('uq_gbp_reviews_business_id'))
    )
    op.create_index(op.f('ix_gbp_reviews_business_id'), 'gbp_reviews', ['business_id'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('input_business_name', sa.String(length=300), nullable=False),
    sa.Column('input_address', sa.Text(), nullable=True),
    sa.Column('input_phone', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('service_areas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('user_keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('client_business_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_business_id'], ['businesses.id'], name=op.f('fk_projects_client_business_id_businesses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('audit_jobs',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_audit_jobs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_jobs'))
    )
    op.create_index(op.f('ix_audit_jobs_project_id'), 'audit_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_jobs_status'), 'audit_jobs', ['status'], unique=False)
    op.create_table('competitors',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('keyword_share', sa.Float(), nullable=False),
    sa.Column('local_pack_count', sa.Integer(), nullable=False),
    sa.Column('local_finder_count', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_competitors_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_competitors_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitors')),
    sa.UniqueConstraint('project_id', 'business_id', name=op.f('uq_competitors_project_id'))
    )
    op.create_index(op.f('ix_competitors_project_id'), 'competitors', ['project_id'], unique=False)
    op.create_table('services',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=True),
    sa.Column('service_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('raw_response_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_services_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_services_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_response_id'], ['data_sources.id'], name=op.f('fk_services_raw_response_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    op.create_index(op.f('ix_services_normalized_name'), 'services', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_services_project_id'), 'services', ['project_id'], unique=False)
    op.create_table('competitor_metrics',
    sa.Column('competitor_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('review_velocity_30d', sa.Float(), nullable=True),
    sa.Column('categories', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('services', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('website_domain', sa.String(length=255), nullable=True),
    sa.Column('local_pack_appearances', sa.Integer(), nullable=True),
    sa.Column('local_finder_appearances', sa.Integer(), nullable=True),
    sa.Column('keyword_overlap', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('raw_response_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_competitor_metrics_competitor_id_competitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_response_id'], ['data_sources.id'], name=op.f('fk_competitor_metrics_raw_response_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitor_metrics'))
    )
    op.create_index(op.f('ix_competitor_metrics_competitor_id'), 'competitor_metrics', ['competitor_id'], unique=False)
    op.create_table('gap_recommendations',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('audit_job_id', sa.Uuid(), nullable=True),
    sa.Column('gap_type', sa.String(length=30), nullable=False),
    sa.Column('client_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('competitor_pattern', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_id'], ['audit_jobs.id'], name=op.f('fk_gap_recommendations_audit_job_id_audit_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_gap_recommendations_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gap_recommendations'))
    )
    op.create_index(op.f('ix_gap_recommendations_project_id'), 'gap_recommendations', ['project_id'], unique=False)
    op.create_table('keywords',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('keyword', sa.String(length=300), nullable=False),
    sa.Column('service', sa.String(length=200), nullable=True),
    sa.Column('location_name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('device', sa.String(length=10), nullable=False),
    sa.Column('search_radius_meters', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_keywords_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_keywords_service_id_services'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keywords')),
    sa.UniqueConstraint('project_id', 'keyword', 'location_name', 'device', name=op.f('uq_keywords_project_id'))
    )
    op.create_index(op.f('ix_keywords_project_id'), 'keywords', ['project_id'], unique=False)
    op.create_table('review_tags',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('tag', sa.String(length=200), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.Column('sentiment', sa.String(length=10), nullable=True),
    sa.Column('mentioned_service_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('raw_response_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['mentioned_service_id'], ['services.id'], name=op.f('fk_review_tags_mentioned_service_id_services'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_response_id'], ['data_sources.id'], name=op.f('fk_review_tags_raw_response_id_data_sources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['gbp_reviews.id'], name=op.f('fk_review_tags_review_id_gbp_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_tags'))
    )
    op.create_index(op.f('ix_review_tags_review_id'), 'review_tags', ['review_id'], unique=False)
    op.create_table('ranking_runs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('keyword_id', sa.Uuid(), nullable=False),
    sa.Column('audit_job_id', sa.Uuid(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('result_type', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('device', sa.String(length=10), nullable=False),
    sa.Column('location_name', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('search_radius_meters', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_response_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_id'], ['audit_jobs.id'], name=op.f('fk_ranking_runs_audit_job_id_audit_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_ranking_runs_keyword_id_keywords'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ranking_runs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_response_id'], ['data_sources.id'], name=op.f('fk_ranking_runs_raw_response_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ranking_runs'))
    )
    op.create_index(op.f('ix_ranking_runs_keyword_id'), 'ranking_runs', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_ranking_runs_project_id'), 'ranking_runs', ['project_id'], unique=False)
    op.create_table('ranking_results',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=True),
    sa.Column('business_name', sa.String(length=300), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('primary_category', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('maps_url', sa.Text(), nullable=True),
    sa.Column('is_client_business', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_ranking_results_business_id_businesses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['ranking_runs.id'], name=op.f('fk_ranking_results_run_id_ranking_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ranking_results'))
    )
    op.create_index(op.f('ix_ranking_results_place_id'), 'ranking_results', ['place_id'], unique=False)
    op.create_index(op.f('ix_ranking_results_run_id'), 'ranking_results', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ranking_results_run_id'), table_name='ranking_results')
    op.drop_index(op.f('ix_ranking_results_place_id'), table_name='ranking_results')
    op.drop_table('ranking_results')
    op.drop_index(op.f('ix_ranking_runs_project_id'), table_name='ranking_runs')
    op.drop_index(op.f('ix_ranking_runs_keyword_id'), table_name='ranking_runs')
    op.drop_table('ranking_runs')
    op.drop_index(op.f('ix_review_tags_review_id'), table_name='review_tags')
    op.drop_table('review_tags')
    op.drop_index(op.f('ix_keywords_project_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_gap_recommendations_project_id'), table_name='gap_recommendations')
    op.drop_table('gap_recommendations')
    op.drop_index(op.f('ix_competitor_metrics_competitor_id'), table_name='competitor_metrics')
    op.drop_table('competitor_metrics')
    op.drop_index(op.f('ix_services_project_id'), table_name='services')
    op.drop_index(op.f('ix_services_normalized_name'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_competitors_project_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_audit_jobs_status'), table_name='audit_jobs')
    op.drop_index(op.f('ix_audit_jobs_project_id'), table_name='audit_jobs')
    op.drop_table('audit_jobs')
    op.drop_table('projects')
    op.drop_index(op.f('ix_gbp_reviews_business_id'), table_name='gbp_reviews')
    op.drop_table('gbp_reviews')
    op.drop_index(op.f('ix_gbp_profiles_place_id'), table_name='gbp_profiles')
    op.drop_index(op.f('ix_gbp_profiles_business_id'), table_name='gbp_profiles')
    op.drop_table('gbp_profiles')
    op.drop_index(op.f('ix_business_locations_business_id'), table_name='business_locations')
    op.drop_table('business_locations')
    op.drop_index(op.f('ix_businesses_domain'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_data_sources_request_hash'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_fetched_at'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_expires_at'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
