"""review nlp fields

Revision ID: dc2f4c69d9bb
Revises: c8e7ef7a265f
Create Date: 2026-10-06 22:28:16.035772
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'dc2f4c69d9bb'
down_revision: str | None = 'c8e7ef7a265f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gbp_reviews', sa.Column('sentiment_score', sa.Float(), nullable=True))
    op.add_column('gbp_reviews', sa.Column('mentioned_services', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('review_tags', sa.Column('sentence', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_tags', 'sentence')
    op.drop_column('gbp_reviews', 'mentioned_services')
    op.drop_column('gbp_reviews', 'sentiment_score')
    # ### end Alembic commands ###
