"""project services and keyword flags

Revision ID: 9205baab9758
Revises: dc2f4c69d9bb
Create Date: 2026-10-06 23:10:45.644443
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '9205baab9758'
down_revision: str | None = 'dc2f4c69d9bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_services',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('user_added', sa.Boolean(), nullable=False),
    sa.Column('user_edited', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('review_mentions', sa.Integer(), nullable=False),
    sa.Column('sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_services_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_services')),
    sa.UniqueConstraint('project_id', 'normalized_name', name=op.f('uq_project_services_project_id'))
    )
    op.create_index(op.f('ix_project_services_project_id'), 'project_services', ['project_id'], unique=False)
    op.add_column('keywords', sa.Column('pattern', sa.String(length=20), nullable=True))
    op.add_column('keywords', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('keywords', sa.Column('project_service_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_keywords_project_service_id_project_services'), 'keywords', 'project_services', ['project_service_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_keywords_project_service_id_project_services'), 'keywords', type_='foreignkey')
    op.drop_column('keywords', 'project_service_id')
    op.drop_column('keywords', 'active')
    op.drop_column('keywords', 'pattern')
    op.drop_index(op.f('ix_project_services_project_id'), table_name='project_services')
    op.drop_table('project_services')
    # ### end Alembic commands ###
